# Finds if true.value is in interval. Will generate a vector of integers from 0 to 3,
# corresponding to the domains generated by the two limits.

#' True value in interval
#'
#' @param df
#' @param lowLim
#' @param upLim
#' @param true.val
#'
#' @return
#' @export
#'
#' @examples
val_in_interval <- function(df, lowLim, upLim, true.val) {
  apply(
    df[, c(lowLim, upLim)],
    1, function(x) {
      x <- sort(x)
      findInterval(true.val, x)
    }
  )
}
